server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine
    username: postgres
    password: texttext
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

indexingSettings:
  sites:
    - url: https://www.skillbox.ru
      name: Skillbox
#    - url: https://www.worldclass.ru
#      name: World Class
#    - url: https://playback.ru
#      name: PlayBack.Ru

  messages:
    stop: Индексация остановлена пользователем
    stopError: Индексация не запущена
    startError: Индексация уже запущена
    indexPageError: Данная страница находится за пределами сайтов, указанных в конфигурационном файле
    searchError: Задан пустой поисковой запрос
    siteNotFound: В базе данных нет сайта
    sitesNotIndexing: Все сайты из конфигурации не проиндексированы
    offsetError: Параметр offset больше длины списка объектов

statisticSettings:
  statuses:
    indexing: INDEXING
    indexed: INDEXED
    failed: FAILED
    warning: WARNING
  statusMessages:
    siteUnavailable: 'Ошибка индексации: сайт не доступен'
    mainPageUnavailable: 'Ошибка индексации: главная страница сайта не доступна'
    ok: ''
    warning: 'Сайт не проиндексирован'

exceptionSettings:
  exceptionMessages:
    badRequest: 'Неправильный запрос'

thread:
  count: 6

connection-settings:
  userAgent: Mozilla/5.0 (Windows; U; WindowsNT5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com

lemmaFinderSettings:
  particlesNamesList:
    - 'МЕЖД'
    - 'ПРЕДЛ'
    - 'СОЮЗ'
    - 'ЧАСТ'

pageRecursiveTaskSettings:
  extensionsList:
    - 'jpg'
    - 'JPG'
    - 'jpeg'
    - 'JPEG'
    - 'gif'
    - 'GIF'
    - 'png'
    - 'PNG'
    - 'pdf'
    - 'PDF'
    - 'svg'
    - 'SVG'
    - 'zip'