server:
  port: 8080
spring:
  datasource:
    username: root
    password: texttext
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexingSettings:
  sites:
    - url: https://lenta.ru
      name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox
    - url: https://playback.ru
      name: PlayBack.Ru
  messages:
    stop: Индексация остановлена пользователем
    stopError: Индексация не запущена
    startError: Индексация уже запущена
    indexPageError: Данная страница находится за пределами сайтов, указанных в конфигурационном файле
  thread-count:
    countOfThread: 100

connection-settings:
  userAgent: Mozilla/5.0 (Windows; U; WindowsNT5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com

lemmaFinderSettings:
  particles-names:
    interjection: МЕЖД
    preposition: ПРЕДЛ
    conjunction: СОЮЗ
    particle: ЧАСТ

db-connection-settings:
  url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  user: root
  password: texttext